name: Distribute to publishers

on:
  release:
    types: [ published ]

jobs:
  upload_asset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: burrunan/gradle-cache-action@v1
        with:
          gradle-distribution-sha-256-sum-warning: false
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          cache: gradle
          java-version: 17
      - name: Get Tag
        id: tag
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './gradle.properties'
          properties: 'mod_version'
      - uses: winterjung/split@v2
        id: split
        with:
          separator: "+"
          msg: ${{steps.tag.outputs.mod_version}}
      - run: |
          echo ${{steps.split.outputs._0}}
          echo ${{steps.split.outputs._1}}
      - run: chmod +x gradlew
      - name: Build
        run: ./gradlew build
      - name: Publish Forge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: "[Forge] Seamless Loading Screen ${{steps.split.outputs._0}}"
          files: forge/build/libs/!(*-@(dev\|sources\|javadoc)).jar
          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: ${{ vars.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.CLASSIC_GITHUB_TOKEN }}
      - name: Publish Fabric
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: "[Fabric] Seamless Loading Screen ${{steps.split.outputs._0}}"
          files: fabric/build/libs/!(*-@(dev\|sources\|javadoc)).jar
          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: ${{ vars.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.CLASSIC_GITHUB_TOKEN }}
